### PR TITLE
Fix for .babylon exported gltf meshes having improper deformation

### LINKED ISSUE #7244: Sandbox export to .babylon file breaks animations
Forum post with context and example:

https://forum.babylonjs.com/t/about-glb-convert-to-babylon/7324

### PR DESCRIPTION
**Pull request by Drigax**
This PR addresses an issue in the babylon scene serialization and deserialization logic for gltf imported meshes. On scene round trip via .babylon format, meshes appear small, improperly oriented and no longer animated by node animation
Issue is caused by helper members `Skeleton.overrideMesh` and `Bone.linkedTransformNode` not being serialized and modified bone serialization indexing logic to match schema used by glTF loader, where glTF coordinate space transform nodes and their associated bones are ignored by the skeleton hierarchy when resolving world transform.

Fixes #7244

### CODE REVIEW

File: src/Meshes/mesh.ts [hunk 1]
```diff
@@ -3449,12 +3450,12 @@ export class Mesh extends AbstractMesh implements IGetSetVerticesData {
         }
 
         // Morph targets
-        if (parsedMesh.morphTargetManagerId > -1) {
```
Comment (deltakosh) [inline src/Meshes/mesh.ts:3452]: why this one? what if id is === 0?

Comment (Drigax) [reply src/Meshes/mesh.ts:3452]: ah, thanks for catching that, I missed copying over my change @L3458

Comment (Drigax) [reply src/Meshes/mesh.ts:3452]: I'll also add a `null` check as well

Comment (Drigax) [reply src/Meshes/mesh.ts]: I didn't realize that `MorphTargetManagerId` can only be int :), reverting that change

**Comment by tskarthikus** [comment]
I am using a glb with animation and trying to export it as such without any alteration.

image

But, the export is having deformations on bones.
It is reprocible in Babylon Sandbox.

image
