### PR TITLE
Fix asset container instantiation with parented instanced nodes

### LINKED ISSUE #13454: instantiateModelsToScene doesn't take parents of clones nodes into account
See https://forum.babylonjs.com/t/proper-way-to-create-an-instance-of-a-loaded-glb/37478/18

### PR DESCRIPTION
**Pull request by carolhmj**
Fix #13454

I don't think there's any way around using some kind of dependency graph to instantiate nodes in the correct order but if anyone has a simpler idea I'd love to hear it :D

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

File: packages/dev/core/src/assetContainer.ts [hunk 1]
```diff
@@ -116,6 +116,110 @@ export class AssetContainer extends AbstractScene {
...
+            // Remove the node from the dependency graph
+            // When a node is visited, we know that dependsOn is empty.
+            // So we only need to remove the node from dependedBy.
+            const dependedByVisitedNode = dependencyGraph.dependedBy.get(nodeToVisit.uniqueId)!;
+            for (const dependedByVisitedNodeId of dependedByVisitedNode) {
+                const dependsOnDependedByVisitedNode = dependencyGraph.dependsOn.get(dependedByVisitedNodeId)!;
+                dependsOnDependedByVisitedNode.delete(nodeToVisit.uniqueId);
+
+                if (dependsOnDependedByVisitedNode.size === 0 && !nodesMarkedForVisit.has(dependedByVisitedNodeId)) {
+                    visitList.push(nodesUidMap.get(dependedByVisitedNodeId)!);
```
Comment (Popov72) [inline packages/dev/core/src/assetContainer.ts:201]: Instead of using a new `nodesMarkedForVisit` set, maybe you can reuse `nodesUidMap` instead and do something like:
```typescript
 if (dependsOnDependedByVisitedNode.size === 0 && nodesUidMap.get(dependedByVisitedNodeId)) {
    visitList.push(nodesUidMap.get(dependedByVisitedNodeId)!);
    nodesUidMap.delete(dependedByVisitedNodeId);
}
```
As an added bonus, at the end you can issue a warning/error if `nodesUidMap` is not empty, which would be an easy way to detect problems in the graph (you can even output the names of problematic nodes if you want).

File: packages/dev/core/src/assetContainer.ts [hunk 2]
```diff
@@ -116,6 +116,110 @@ export class AssetContainer extends AbstractScene {
...
+                    nodesMarkedForVisit.add(dependedByVisitedNodeId);
+                }
+            }
+        }
+
+        return sortedNodes;
+    }
+
+    private _addNodeAndDescendantsToList(list: Node[], addedIds: Set<number>, rootNode: Node, predicate?: (entity: any) => boolean) {
+        if ((predicate && predicate(rootNode)) || addedIds.has(rootNode.uniqueId)) {
```
Comment (Popov72) [inline packages/dev/core/src/assetContainer.ts:211]: Shouldn't it be `!predicate(rootNode)` instead of `predicate(rootNode)`?

File: packages/dev/core/src/assetContainer.ts [hunk 3]
```diff
@@ -173,29 +277,43 @@ export class AssetContainer extends AbstractScene {
...
+                if (replicatedParent) {
+                    clone.parent = replicatedParent;
+                } else {
+                    clone.parent = source.parent;
+                }
+            }
+
+            clone.position = source.position.clone();
+            clone.rotation = source.rotation.clone();
+            clone.scaling = source.scaling.clone();
```
Comment (Popov72) [inline packages/dev/core/src/assetContainer.ts:315]: Do we really need to do that? clone is coming from a call to `createInstance()` or `clone()`, so these properties should already be ok?

File: packages/dev/core/src/assetContainer.ts [hunk 4]
```diff
@@ -242,42 +360,29 @@ export class AssetContainer extends AbstractScene {
...
-                    if (instancesExist && newOne.getClassName() !== "InstancedMesh") {
-                        instanceSourceMap[idx] = newOne;
-                    }
-                    result.rootNodes.push(newOne);
+        sortedNodes.forEach((node) => {
+            if (node.getClassName() === "InstancedMesh") {
+                const instancedNode = node as InstancedMesh;
+                const sourceMesh = instancedNode.sourceMesh;
+                const replicatedSourceId = conversionMap[sourceMesh.uniqueId];
+                const replicatedSource = replicatedSourceId ? storeMap[replicatedSourceId] : sourceMesh;
```
Comment (Popov72) [inline packages/dev/core/src/assetContainer.ts:374]: Is it possible that `conversionMap[sourceMesh.uniqueId] == 0`? If yes, you probably want to check `replicatedSourceId !== undefined ? ...` instead.

File: packages/dev/core/src/assetContainer.ts [hunk 5]
```diff
@@ -242,42 +360,29 @@ export class AssetContainer extends AbstractScene {
...
+                onNewCreated(instancedNode, replicatedInstancedNode);
+            } else {
+                // Mesh or TransformNode
+                const canInstance = !options?.doNotInstantiate && node.getClassName() === "Mesh" && (node as Mesh).getTotalVertices() > 0;
+                const replicatedNode = canInstance ? (node as Mesh).createInstance(node.name) : (node as TransformNode).clone(node.name, null, true);
+                if (!replicatedNode) {
+                    console.error("Could not clone or instantiate node on Asset Container", node.name);
+                    return;
                 }
+                onNewCreated(node as TransformNode, replicatedNode as TransformNode);
```
Comment (Popov72) [inline packages/dev/core/src/assetContainer.ts:385]: nit: Maybe you could use `TransformNode` instead of `Node` in the new code? That would avoid the 3 "as TransformNode" casts

File: packages/dev/core/src/assetContainer.ts [hunk 6]
```diff
@@ -376,7 +481,7 @@ export class AssetContainer extends AbstractScene {
             if (predicate && !predicate(o)) {
                 return;
             }
-            this.scene.addMesh(o);
+            this.scene.addMesh(o, true);
```
Comment (Popov72) [inline packages/dev/core/src/assetContainer.ts:484]: Was it a bug in the previous code?

I would have thought that `this.meshes` contains all the meshes, so there's no need to recursively add, all meshes will eventually be added to the scene?

Moreover, by using the recursive flag, all descendants of `o` won't be checked by the predicate.

File: packages/dev/core/src/assetContainer.ts [hunk 7]
```diff
@@ -484,7 +589,7 @@ export class AssetContainer extends AbstractScene {
             if (predicate && !predicate(o)) {
                 return;
             }
-            this.scene.removeMesh(o);
+            this.scene.removeMesh(o, true);
```
Comment (Popov72) [inline packages/dev/core/src/assetContainer.ts:592]: Same question than above.

**Review by Popov72 — COMMENTED** [review]
Only a few comments, great work!

File: packages/dev/core/src/assetContainer.ts (hunk 3 above)
Comment (carolhmj) [reply packages/dev/core/src/assetContainer.ts:315]: You're right, we don't need to clone

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

File: packages/dev/core/src/assetContainer.ts [hunk 8]
```diff
@@ -310,9 +313,9 @@ export class AssetContainer extends AbstractScene {
                 }
             }
 
-            clone.position = source.position.clone();
-            clone.rotation = source.rotation.clone();
-            clone.scaling = source.scaling.clone();
+            clone.position = source.position;
+            clone.rotation = source.rotation;
+            clone.scaling = source.scaling;
```
Comment (Popov72) [inline packages/dev/core/src/assetContainer.ts:318]: You should not even need to do this, the position/rotation/scaling properties of the clone should already have the right values. On the contrary, setting the same position/rotation/scaling objects as the source will link the clone and the source: when you update the values of one, the other will be updated too as there are the same objects.

**Review by Popov72 — CHANGES_REQUESTED** [review]

File: packages/dev/core/src/assetContainer.ts (hunk 8 above)
Comment (carolhmj) [reply packages/dev/core/src/assetContainer.ts:318]: If I don't set it through, the positions aren't updated correctly. Maybe it's because the asset container is cloning to a different scene?

File: packages/dev/core/src/assetContainer.ts (hunk 6 above)
Comment (carolhmj) [reply packages/dev/core/src/assetContainer.ts:487]: I was a bit unsure about what should the expected behavior here, because the user could manually add just some of the meshes in the hierarchy to the container, and in this case currently addAll/removeAll will only affect the manually added meshes: https://playground.babylonjs.com/#5NFRVE#160 while instantiateAll will add all meshes.

**Review by Popov72 — CHANGES_REQUESTED** [review]
Shouldn't we use the same default naming than before when cloning / instantiating new nodes? i.e., adding "Clone of " or "instance of" as `instantiateHierarchy` is doing, to avoid a breaking change?

File: packages/dev/core/src/assetContainer.ts (hunk 6 above)
Comment (carolhmj) [reply packages/dev/core/src/assetContainer.ts:487]: Fair, I can remove the true and create an issue for tracking?

File: packages/dev/core/src/assetContainer.ts (hunk 8 above)
Comment (carolhmj) [reply packages/dev/core/src/assetContainer.ts:318]: That's because instantiateModels uses `instantiateHierarchy` currently and that does copy the positions and scaling: https://github.com/BabylonJS/Babylon.js/blob/master/packages/dev/core/src/Meshes/mesh.ts#L743

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

File: packages/dev/core/src/assetContainer.ts (hunk 6 above)
Comment (carolhmj) [reply packages/dev/core/src/assetContainer.ts]: Created issue: https://github.com/BabylonJS/Babylon.js/issues/13477

File: packages/dev/core/src/assetContainer.ts (hunk 8 above)
Comment (Popov72) [reply packages/dev/core/src/assetContainer.ts:319]: I have just rechecked and it does work without the 3 lines of code, in both the clone and instance mode. Can you recheck on your end?

For me, the code in `instantiateHierarchy` is not necessary either.

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

File: packages/dev/core/src/assetContainer.ts (hunk 8 above)
Comment (Popov72) [reply packages/dev/core/src/assetContainer.ts]: My bad, we need to copy + clone when the source mesh is in fact an instance.

**Review by Popov72 — APPROVED** [review]

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Review by sebavan — APPROVED** [review]

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/13467/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13467/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13467/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/13467/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/13467/merge
https://gui.babylonjs.com/?snapshot=refs/pull/13467/merge
https://nme.babylonjs.com/?snapshot=refs/pull/13467/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/13467/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for webgl1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13467/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

File: packages/dev/core/src/assetContainer.ts (hunk 8 above)
Comment (RaananW) [reply packages/dev/core/src/assetContainer.ts]: Is this resolved?

File: packages/dev/core/src/assetContainer.ts [hunk 9]
```diff
@@ -173,29 +282,43 @@ export class AssetContainer extends AbstractScene {
...
+                if (replicatedParent) {
+                    clone.parent = replicatedParent;
+                } else {
+                    clone.parent = source.parent;
+                }
+            }
+
+            clone.position = source.position.clone();
+            clone.rotation = source.rotation.clone();
+            clone.scaling = source.scaling.clone();
```
Comment (RaananW) [inline packages/dev/core/src/assetContainer.ts:320]: Is there a need to clone here? There is a resolved comment that said we don't need, but this is still here.

Anyhow - `.copyFrom` will be more efficient than `clone()`, as those properties are already defined.

File: packages/dev/core/src/assetContainer.ts [hunk 10]
```diff
@@ -242,42 +365,29 @@ export class AssetContainer extends AbstractScene {
...
+                const replicatedSourceId = conversionMap[sourceMesh.uniqueId];
+                const replicatedSource = replicatedSourceId !== undefined ? storeMap[replicatedSourceId] : sourceMesh;
+                const replicatedInstancedNode = replicatedSource.createInstance(instancedNode.name);
+                onNewCreated(instancedNode, replicatedInstancedNode);
+            } else {
+                // Mesh or TransformNode
+                const canInstance = !options?.doNotInstantiate && (node as Mesh)._isMesh;
+                const replicatedNode = canInstance ? (node as Mesh).createInstance("instance of " + node.name) : node.clone("Clone of " + node.name, null, true);
+                if (!replicatedNode) {
+                    console.error("Could not clone or instantiate node on Asset Container", node.name);
```
Comment (RaananW) [inline packages/dev/core/src/assetContainer.ts:387]: avoid using console. Use the logging service in Tools instead

Comment (RaananW) [reply packages/dev/core/src/assetContainer.ts:387]: Also - should this not throw? I mean - is that not an issue that will prevent the process to work correctly?

File: packages/dev/core/src/assetContainer.ts [hunk 11]
```diff
@@ -242,42 +365,29 @@ export class AssetContainer extends AbstractScene {
...
+                const instancedNode = node as InstancedMesh;
+                const sourceMesh = instancedNode.sourceMesh;
+                const replicatedSourceId = conversionMap[sourceMesh.uniqueId];
+                const replicatedSource = replicatedSourceId !== undefined ? storeMap[replicatedSourceId] : sourceMesh;
+                const replicatedInstancedNode = replicatedSource.createInstance(instancedNode.name);
+                onNewCreated(instancedNode, replicatedInstancedNode);
+            } else {
+                // Mesh or TransformNode
+                const canInstance = !options?.doNotInstantiate && (node as Mesh)._isMesh;
+                const replicatedNode = canInstance ? (node as Mesh).createInstance("instance of " + node.name) : node.clone("Clone of " + node.name, null, true);
```
Comment (RaananW) [inline packages/dev/core/src/assetContainer.ts:385]: nit picky - Use templates literals instead of " " + `stringToAdd`

File: packages/dev/core/src/assetContainer.ts [hunk 12]
```diff
@@ -242,42 +365,29 @@ export class AssetContainer extends AbstractScene {
...
-                    if (instancesExist && newOne.getClassName() !== "InstancedMesh") {
-                        instanceSourceMap[idx] = newOne;
-                    }
-                    result.rootNodes.push(newOne);
+        sortedNodes.forEach((node) => {
+            if (node.getClassName() === "InstancedMesh") {
+                const instancedNode = node as InstancedMesh;
+                const sourceMesh = instancedNode.sourceMesh;
+                const replicatedSourceId = conversionMap[sourceMesh.uniqueId];
+                const replicatedSource = replicatedSourceId !== undefined ? storeMap[replicatedSourceId] : sourceMesh;
```
Comment (RaananW) [inline packages/dev/core/src/assetContainer.ts:379]: `typeof  replicatedSourceId === "number"` will be safer here. This is, however, very low priority. There shouldn't be anything other than numbers in this object.

**Review by RaananW — COMMENTED** [review]
Great! Just a few comments

File: packages/dev/core/src/assetContainer.ts (hunk 9 above)
Comment (carolhmj) [reply packages/dev/core/src/assetContainer.ts:320]: Yup, we do need to clone on the case of instances, but I'll put the copyFrom.

File: packages/dev/core/src/assetContainer.ts (hunk 10 above)
Comment (carolhmj) [reply packages/dev/core/src/assetContainer.ts:387]: I wasn't sure what would be preferred, but I can throw.

Comment (RaananW) [reply packages/dev/core/src/assetContainer.ts]: Depends on the use case to be honest. If it can continue - leave the console. otherwise, throw and let the user handle the error.

**Review by RaananW — APPROVED** [review]

**Comment by aWeirdo** [comment]
I think this broke something when using AssetContainer.instantiateModelsToScene()
Started getting spammed with logger messages "Instances should only be created for meshes with geometry."

All meshes and rootNodes added by *instantiateModelsToScene* now tagged as "isAnInstance" when running the following code in console

    scene.meshes.forEach( (mesh) => {
        console.error(mesh.name, mesh.isAnInstance)
    })

and animations can no longer be played separately,

check console (might need to hard reload), should show the logger message spam, the heads are also supposed to move/animate independently of each other (delayed), check the 4.2.1 bjs version
https://playground.babylonjs.com/#S7E00P
