### PR TITLE
Node Material Editor: Allow loading GLTF format files in preview window, add drag and drop, revert to cube when loading fails

### LINKED ISSUE #12752: Support loading of GLTF files in NME
Related issue: https://forum.babylonjs.com/t/nme-cant-upload-custom-gltf-for-preview/32172/2

As a bonus, it would be nice if we could structure the file loading in a common way so that we could reuse this across multiple tools - like the sandbox, the NME and the VSM

Add Drag and Drop for file loading in NME?

### PR DESCRIPTION
**Pull request by carolhmj**
Close #12752

To load a GLTF, you have to select all of its files in the file input/drag and drop all the files.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Review by sebavan — COMMENTED** [review]
LGTM but lets wait on @RaananW eagle eyes :-)

File: packages/tools/nodeEditor/src/components/preview/previewManager.ts [hunk 1]
```diff
@@ -159,6 +160,44 @@ export class PreviewManager {
...
+            null,
+            null,
+            null,
+            null,
+            () => {
+                this._globalState.previewType = PreviewType.Box;
+                this._globalState.listOfCustomPreviewFiles = [];
+                this._scene.meshes.forEach((m) => m.dispose());
+                this._globalState.onRefreshPreviewMeshControlComponentRequiredObservable.notifyObservers();
+                this._refreshPreviewMesh(true);
```
Comment (RaananW) [inline packages/tools/nodeEditor/src/components/preview/previewManager.ts:180]: this belongs in a "reset" function (if not already exists)

File: packages/tools/nodeEditor/src/components/preview/previewManager.ts [hunk 2]
```diff
@@ -159,6 +160,44 @@ export class PreviewManager {
...
+            };
+            canvas.addEventListener("dragenter", onDrag, false);
+            canvas.addEventListener("dragover", onDrag, false);
+
+            const onDrop = (evt: DragEvent) => {
+                evt.stopPropagation();
+                evt.preventDefault();
+                this._globalState.onDropEventReceivedObservable.notifyObservers(evt);
+            };
+            canvas.addEventListener("drop", onDrop, false);
```
Comment (RaananW) [inline packages/tools/nodeEditor/src/components/preview/previewManager.ts:198]: this entire part can be the responsibility of the filesinput module. It listens to the events and triggers the loadFiles. Unless there is a reason not to use it?

File: packages/tools/nodeEditor/src/components/preview/previewMeshControlComponent.tsx [hunk 3]
```diff
@@ -51,14 +63,14 @@ export class PreviewMeshControlComponent extends React.Component<IPreviewMeshCon
     }
 
     useCustomMesh(evt: any) {
-        const files: File[] = evt.target.files;
+        const files: File[] = evt.target?.files || evt.dataTransfer?.files;
         if (files && files.length) {
             const file = files[0];
```
Comment (RaananW) [inline packages/tools/nodeEditor/src/components/preview/previewMeshControlComponent.tsx:68]: just wondering if this is still correct (just in case you don't want to use the files input). is the model file always the first one?

Comment (RaananW) [reply packages/tools/nodeEditor/src/components/preview/previewMeshControlComponent.tsx:68]: (sorry, actually meant two lines down)

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/13842/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13842/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13842/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/13842/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/13842/merge
https://gui.babylonjs.com/?snapshot=refs/pull/13842/merge
https://nme.babylonjs.com/?snapshot=refs/pull/13842/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/13842/merge#BCU1XR#0

File: packages/tools/nodeEditor/src/components/preview/previewManager.ts (hunk 2 above)
Comment (carolhmj) [reply packages/tools/nodeEditor/src/components/preview/previewManager.ts:198]: I wanted both the drag and drop listener and the already existing file selection to take the same path (on PreviewMeshControlComponent.useCustomMesh), so that's why I didn't use the monitorForDragAndDrop, as it always calls loadFiles.

File: packages/tools/nodeEditor/src/components/preview/previewMeshControlComponent.tsx (hunk 3 above)
Comment (carolhmj) [reply packages/tools/nodeEditor/src/components/preview/previewMeshControlComponent.tsx:68]: PreviewFile isn't used by the mesh loading anymore, but it's used by the particle system so that's why I left it there. In the case of the mesh loading, it's going to always load all files.

**Review by RaananW — APPROVED** [review]
