### PR TITLE
Fix loading of GUIs with custom fonts and add font controls to InputText and InputPassword

### LINKED ISSUE #13125: Add Text control parameters to containers missing them
Forum issue: https://forum.babylonjs.com/t/gui-editor-inputtext-is-now-missing-font-selection/33370
The controls missing font control parameters are:
- InputText
- InputPassword

### PR DESCRIPTION
**Pull request by carolhmj**
Fixes #13125

### CODE REVIEW

File: packages/tools/guiEditor/src/components/propertyTab/propertyGrids/gui/commonControlPropertyGridComponent.tsx [hunk 1]
```diff
@@ -93,6 +96,8 @@ export class CommonControlPropertyGridComponent extends React.Component<ICommonC
                       { label: "Brush Script MT", value: 9 },
                   ],
             value: 0,
+            invalidFonts: JSON.parse(String(window.sessionStorage.getItem("invalidFonts"))) ? JSON.parse(String(window.sessionStorage.getItem("invalidFonts"))) : [],
```
Comment (Popov72) [inline packages/tools/guiEditor/src/components/propertyTab/propertyGrids/gui/commonControlPropertyGridComponent.tsx:99]: You should do:
```typescript
invalidFonts: JSON.parse(String(window.sessionStorage.getItem("invalidFonts"))) ?? []
```
to avoid evaluating the expression two times.

**Review by Popov72 — APPROVED** [review]

**Review by sebavan — APPROVED** [review]

File: packages/tools/guiEditor/src/components/propertyTab/propertyGrids/gui/commonControlPropertyGridComponent.tsx (hunk 1 above)
Comment (carolhmj) [reply packages/tools/guiEditor/src/components/propertyTab/propertyGrids/gui/commonControlPropertyGridComponent.tsx]: done!
