### PR TITLE
Fix #12084

### LINKED ISSUE #12084: Potential memory leak - event listener not removed when scene disposed
The following code:

```javascript
            const camera = new BABYLON.UniversalCamera("camera1", new BABYLON.Vector3(0, 5, -10), scene);
            camera.setTarget(BABYLON.Vector3.Zero());
            camera.attachControl(true);
```

registers 3 gamepadconnected events. out of those 3 only 2 are unregistered when the scene is disposed. The following is the stacktrace of those 3 `addEventListener` calls:

```
      at addEventListener (webpack:/BABYLON/lts/core/generated/DeviceInput/InputDevices/webDeviceInputSystem.ts:691:15)
      at _handleGamepadActions (webpack:/BABYLON/lts/core/generated/DeviceInput/InputDevices/webDeviceInputSystem.ts:158:17)
      at _configureEvents (webpack:/BABYLON/lts/core/generated/DeviceInput/InputDevices/webDeviceInputSystem.ts:85:13)
      at new (webpack:/BABYLON/lts/core/generated/DeviceInput/InputDevices/internalDeviceSourceManager.ts:62:38)
      at Function._Create (webpack:/BABYLON/lts/core/generated/DeviceInput/InputDevices/internalDeviceSourceManager.ts:45:42)
      at _Create (webpack:/BABYLON/lts/core/generated/DeviceInput/InputDevices/deviceSourceManager.ts:51:64)
      at $i.attachControl (webpack:/BABYLON/lts/core/generated/Inputs/scene.inputManager.ts:504:40)
      at attachControl (webpack:/BABYLON/lts/core/generated/scene.ts:1566:27)
      at attachControl (webpack:/BABYLON/lts/core/generated/scene.ts:1294:17)
      >>
      at EventTarget.addEventListener (__puppeteer_evaluation_script__:13:19)
      at addEventListener (webpack:/BABYLON/lts/core/generated/Gamepads/gamepadManager.ts:107:31)
      at ns.get (webpack:/BABYLON/lts/core/generated/Gamepads/gamepadSceneComponent.ts:27:35)
      at gamepadManager (webpack:/BABYLON/lts/core/generated/Cameras/Inputs/freeCameraGamepadInput.ts:69:47)
      at attachControl (webpack:/BABYLON/lts/core/generated/Cameras/cameraInputsManager.ts:198:31)
      at attachElement (webpack:/BABYLON/lts/core/generated/Cameras/freeCamera.ts:281:20)
      at __puppeteer_evaluation_script__:7:20
      >>
      at EventTarget.addEventListener (__puppeteer_evaluation_script__:13:19)
      at addEventListener (webpack:/BABYLON/lts/core/generated/Gamepads/gamepadManager.ts:107:31)
      at ns.get (webpack:/BABYLON/lts/core/generated/Gamepads/gamepadSceneComponent.ts:27:35)
      at gamepadManager (webpack:/BABYLON/lts/core/generated/Cameras/Inputs/freeCameraGamepadInput.ts:103:31)
      at detachControl (webpack:/BABYLON/lts/core/generated/Cameras/cameraInputsManager.ts:209:31)
      at detachElement (webpack:/BABYLON/lts/core/generated/Cameras/freeCamera.ts:298:20)
      at detachControl (webpack:/BABYLON/lts/core/generated/scene.ts:3952:36)

```

It seems like dispose registers a new event instead of only removing it.

### PR DESCRIPTION
**Pull request by deltakosh**

### CODE REVIEW

File: src/scene.ts [hunk 1]
```diff
@@ -4625,6 +4621,11 @@ export class Scene extends AbstractScene implements IAnimatable, IClipPlanesHold
         // Post-processes
         this.postProcessManager.dispose();
 
+        // Components
+        for (let component of this._components) {
```
Comment (deltakosh) [inline src/scene.ts:4625]: Overall the gamepad component was removed from the list and thus when the camera is disposing the gamepad handlers it was forcing the creation of a new gamepad component ;)

**Review by sebavan — APPROVED** [review]

**Review by RaananW — APPROVED** [review]
