### PR TITLE
Animation reset fix

### LINKED ISSUE #4174: glTF animation channels can cross modify other channels
- Expected result: Animation channels do not influence each other when loading from a glTF model
- Actual result: Animation channels influence each other when loading from a glTF model

The glTF model is attached below:
[testModel.zip](https://github.com/BabylonJS/Babylon.js/files/1934034/testModel.zip)

### PR DESCRIPTION
**Pull request by bghgary**
_Engine fixes_
* Fix bug with animations not resetting back to original value (fixes #4174). I also reverted the code to allow animations to apply to multiple targets as with blending since it doesn't work in all cases.

@deltakosh Please review the animations change. I have tested blending with https://www.babylonjs-playground.com/#IQN716#9.

### CODE REVIEW

File: src/Animations/babylon.runtimeAnimation.ts [hunk 1]
```diff
@@ -212,36 +217,19 @@
...
-        private _setValue(target: any, currentValue: any, weight = 1.0): void {
             // Set value
             var path: any;
             var destination: any;
 
             let targetPropertyPath = this._animation.targetPropertyPath
 
             if (targetPropertyPath.length > 1) {
-                var property = target[targetPropertyPath[0]];
+                var property = this._target;
```
Comment (deltakosh) [inline src/Animations/babylon.runtimeAnimation.ts]: On my phone but don't we miss the first part of the path?

Comment (bghgary) [reply src/Animations/babylon.runtimeAnimation.ts]: Oops. Will fix.

**Comment by bghgary** [comment]
I've split the getVerticesData into a separate PR. @sebavan already merged the sandbox fixes.

File: src/Animations/babylon.runtimeAnimation.ts [hunk 2]
```diff
@@ -272,27 +274,7 @@
                         this._originalBlendValue = originalValue;
                     }
                 }
-            }
-
-            if (weight !== -1.0) {
```
Comment (bghgary) [inline src/Animations/babylon.runtimeAnimation.ts]: This used to get the original value only when weight is not -1.0. Is the original value intended to be the original value before blending? My new code does not check weight because I want to be able to reset the value back to the original value before setValue is ever called. Should I use separate variables for this?

Comment (deltakosh) [reply src/Animations/babylon.runtimeAnimation.ts]: Unfortunately it is a bit trickier as the current value read and store in the original value is the value of the target at current time.
If an animation was already animating the target the you will get the current value computed from the animation.

This is why I think we should just get animation.keys[0].value (which was the intend of animate(0) but I think we can safely use first value

**Comment by deltakosh** [comment]
Something like that:
image

**Comment by bghgary** [comment]
That won't work to fix the issue I'm trying to fix. The issue I'm trying to fix is to restore the target back to the value before animation is applied.

**Comment by deltakosh** [comment]
But is it the responsibility of the animation to do that?
