### PR TITLE
No more hacky fix for CreateForMesh serialization

### LINKED ISSUE #11605: Advance Texture Bug, Babylon file appears to save incorrectly.
Saving the scene as babylon file loads incorrectly in sandbox. The sandbox’s output is not matching with PG sample’s output.

https://forum.babylonjs.com/t/advanced-texture-bug/25859

### PR DESCRIPTION
**Pull request by darraghjburke**
Makes CreateForMesh generate textures and materials with unique names, using the mesh name + a unique ID.

Fixes #11605.

In future we should probably make material serialization more name-conflict proof. This is a hotfix for a specific broken behavior, but doesn't address the bigger problem.

### CODE REVIEW

File: gui/src/2D/advancedDynamicTexture.ts [hunk 1]
```diff
@@ -1149,8 +1149,11 @@ export class AdvancedDynamicTexture extends DynamicTexture {
      * @returns a new AdvancedDynamicTexture
      */
     public static CreateForMesh(mesh: AbstractMesh, width = 1024, height = 1024, supportPointerMove = true, onlyAlphaTesting = false, invertY?: boolean): AdvancedDynamicTexture {
-        var result = new AdvancedDynamicTexture(mesh.name + " AdvancedDynamicTexture", width, height, mesh.getScene(), true, Texture.TRILINEAR_SAMPLINGMODE, invertY);
-        var material = new StandardMaterial("AdvancedDynamicTextureMaterial", mesh.getScene());
+        // use a unique ID in name so serialization will work even if you create two ADTs for a single mesh
+        // TODO: find a better solution for material serialization
+        const uniqueId = mesh.getScene().getUniqueId();
+        var result = new AdvancedDynamicTexture(`AdvancedDynamicTexture for ${mesh.name} [${uniqueId}]`, width, height, mesh.getScene(), true, Texture.TRILINEAR_SAMPLINGMODE, invertY);
```
Comment (deltakosh) [inline gui/src/2D/advancedDynamicTexture.ts:1155]: we can use our UUID generator here I believe

Comment (darraghjburke) [reply gui/src/2D/advancedDynamicTexture.ts:1155]: Done

**Review by deltakosh — APPROVED** [review]
