### PR TITLE
Fix #11943

### LINKED ISSUE #11943: Mesh instances broken without hardware instancing support
**Repro**
- Bug repro: https://playground.babylonjs.com/#MSAHKR#33
- Expected result: Three meshes showing
- Current result: Only one mesh is showing

Note that in LH mode, the same problem doesn't happen.

### PR DESCRIPTION
**Pull request by deltakosh**

### CODE REVIEW

**Review by RaananW — APPROVED** [review]

File: src/Meshes/mesh.ts [hunk 1]
```diff
@@ -515,6 +515,16 @@ export class Mesh extends AbstractMesh implements IGetSetVerticesData {
...
 
+        this._onBeforeDraw = ((isInstance: boolean, world: Matrix, effectiveMaterial?: Material) => {
+            if (isInstance && effectiveMaterial) {
+                if (this._uniformBuffer) {
+                    this.transferToEffect(world);
+                } else {
+                    effectiveMaterial.bindOnlyWorldMatrix(world);
+                }
+            }
+        }).bind(this);
```
Comment (RaananW) [inline src/Meshes/mesh.ts:526]: probably no need for the bind, but it works with it as well :-)

Comment (deltakosh) [reply src/Meshes/mesh.ts:526]: It is required because of the way we call it

Comment (deltakosh) [reply src/Meshes/mesh.ts:526]: As I want to avoid using an arrow function each time it is called
