### PR TITLE
Node Material Editor: Fix automatic creation of inputs for "sourceY" …

### LINKED ISSUE #13761: Dragging biplanar node's second image input and clicking creates infinite blocks
**Repro**
- Bug repro on [playground](https://playground.babylonjs.com): https://nme.babylonjs.com/#AHU7HJ

When dragging the bottom image input and clicking, a node is created, but instead of creating a line between the two, you can still drag around and click more:

nme-biplanar-drag

### PR DESCRIPTION
**Pull request by carolhmj**
…and "sourceZ"

Fix #13761

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/13773/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13773/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13773/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/13773/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/13773/merge
https://gui.babylonjs.com/?snapshot=refs/pull/13773/merge
https://nme.babylonjs.com/?snapshot=refs/pull/13773/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/13773/merge#BCU1XR#0

File: packages/dev/sharedUiComponents/src/nodeGraphSystem/graphCanvas.tsx [hunk 1]
```diff
@@ -1248,6 +1248,20 @@ export class GraphCanvasComponent extends React.Component<IGraphCanvasComponentP
...
+                    const outputBlockType = outputData._blockType;
+                    if (outputBlockType === pointB.data._blockType) {
+                        pointA = output;
+                        break;
+                    }
+                }
+            }
+            if (!pointA) {
+                return;
+            }
```
Comment (RaananW) [inline packages/dev/sharedUiComponents/src/nodeGraphSystem/graphCanvas.tsx:1264]: This can move inside the last if. Otherwise, as an overview, it looks a bit off - you are checking for the same thing you checked in the last if statement

File: packages/dev/core/src/Materials/Node/nodeMaterialConnectionPointCustomObject.ts [hunk 2]
```diff
@@ -19,7 +19,8 @@ export class NodeMaterialConnectionPointCustomObject<T extends NodeMaterialBlock
         name: string,
         ownerBlock: NodeMaterialBlock,
         direction: NodeMaterialConnectionPointDirection,
-        private _blockType: new (...args: any[]) => T,
+        // @internal
+        public _blockType: new (...args: any[]) => T,
```
Comment (RaananW) [inline packages/dev/core/src/Materials/Node/nodeMaterialConnectionPointCustomObject.ts:23]: Is there no parent class for all block types?

Comment (carolhmj) [reply packages/dev/core/src/Materials/Node/nodeMaterialConnectionPointCustomObject.ts:23]: The thing here is that this is the blockType constructor, and I didn't want to change typing to avoid affecting anything else 😬

**Review by RaananW — APPROVED** [review]

**Review by Popov72 — APPROVED** [review]
