### PR TITLE
Fix camera collisions for RHS scenes with GLTF models

### LINKED ISSUE #11688: Incorrect camera collisions when scene is right handed
Forum discussion: https://forum.babylonjs.com/t/problem-when-checkcollisions-and-userighthandedsystem-are-used-together/26248

**Repro**
- Bug repro on [playground](https://playground.babylonjs.com): https://www.babylonjs-playground.com/#I6J7UZ#47
- Expected result: Player should be able to walk on the ground
- Current result: Player clips through the mesh

**Additional context**
Doesn't seem to happen when using a plane ground or even a ground created from a height map: https://playground.babylonjs.com/#LQ4LI1#131

### PR DESCRIPTION
**Pull request by carolhmj**
Fix #11688

With the fix, collisions happen normally on the example playground: https://www.babylonjs-playground.com/#I6J7UZ#47

### CODE REVIEW

File: src/Collisions/collider.ts [hunk 1]
```diff
@@ -426,7 +434,7 @@ export class Collider {
 
         pos.addInPlace(this._displacementVector);
         this.intersectionPoint.addInPlace(this._displacementVector);
-
+
```
Comment (sebavan) [inline src/Collisions/collider.ts:437]: should not be here :-)

File: src/Meshes/abstractMesh.ts [hunk 2]
```diff
@@ -1718,7 +1724,7 @@ export class AbstractMesh extends TransformNode implements IDisposable, ICullabl
         // Transformation matrix
         const collisionsScalingMatrix = TmpVectors.Matrix[0];
         const collisionsTransformMatrix = TmpVectors.Matrix[1];
-        Matrix.ScalingToRef(1.0 / collider._radius.x, 1.0 / collider._radius.y, 1.0 / collider._radius.z, collisionsScalingMatrix);
+        Matrix.ScalingToRef(1.0 / collider._radius.x, 1.0 / collider._radius.y, 1.0 / collider._radius.z, collisionsScalingMatrix);
```
Comment (sebavan) [inline src/Meshes/abstractMesh.ts:1727]: Trailing space

File: src/Meshes/mesh.ts [hunk 3]
```diff
@@ -4501,6 +4501,11 @@ export class Mesh extends AbstractMesh implements IGetSetVerticesData {
             this.instances.pop();
         }
     }
+
+    /** @hidden */
+    public _shouldConvertRHS() {
+        return this.overrideMaterialSideOrientation === Material.CounterClockWiseSideOrientation;
```
Comment (sebavan) [inline src/Meshes/mesh.ts:4507]: I am wondering if it is always true when for instance scaling is -1 on one axis only, determinant of the matrix being negative ???

Comment (Popov72) [reply src/Meshes/mesh.ts:4507]: The problem is with geometries that are described in rhs because the collision code expects it to be lhs.

When loading a glTF mesh with `scene.useRightHandedSystem=false` everything is ok because the root node the loader creates has a transformation that transforms the rhs geometry to lhs. However, when `scene.useRightHandedSystem=true` the loader sets an identity transformation and the rhs geometry stays rhs. That's the case we need to detect.

When a mesh is loaded by the glTF loader, we can detect this case by testing `this.overrideMaterialSideOrientation === Material.CounterClockWiseSideOrientation` (see https://github.com/BabylonJS/Babylon.js/issues/11688#issuecomment-1002219692), hence the test in @carolhmj code.

Apart from glTF, we normally don't handle rhs geometries so we don't have the problem. The problem can only arise if a user is creating "by hand" a rhs geometry and does not set a transformation that transforms the geometry from rhs to  lhs. But in that case the user would have to do the same thing than the glTF loader and set `overrideMaterialSideOrientation = Material.CounterClockWiseSideOrientation` else the geometry would be inside out.

Comment (deltakosh) [reply src/Meshes/mesh.ts:4507]: > That's the case we need to detect

Yes I agree and then why not testing `scene.useRightHandedSystem=true`

Comment (Popov72) [reply src/Meshes/mesh.ts:4507]: Because meshes not loded with the glTF loader will also have `scene.useRightHandedSystem==true` but they should not trigger the alternate collision code because their geometry is lhs.

Comment (deltakosh) [reply src/Meshes/mesh.ts:4507]: well if you create the mesh in RH mode you will have to invert them to display correctly right? I get that you can override the materialSideOrientation but you can also create them with RH in mind.

Comment (Popov72) [reply src/Meshes/mesh.ts:4507]: What do you mean by
> you will have to invert them to display correctly right?

and

> but you can also create them with RH in mind.

?

If the geometry is in rhs, you can either list the vertex indices backward (compared to creating a lhs geometry) or set the `sideOrientation` accordingly. However, I don't think the first solution is the right one because you should order the indices so that the triangle displays correctly in a rhs system when you create a rhs geometry. That's what happens in glTF: the vertex positions and indices are described in a rhs system and the glTF loader does not change them, it updates the `sideOrientation` property instead.

Comment (deltakosh) [reply src/Meshes/mesh.ts:4507]: Yes that what I meant: you could create your geometry to work directly with RH (inverting indices). But in the nutshell, what I try to say is that testing scene.useRightHanded should suffice because I do not expect to have LH models in that mode

Comment (carolhmj) [reply src/Meshes/mesh.ts:4507]: Thanks for bringing this to attention Seb, I think there are two cases here, depending if the vertex data from the mesh comes from a GLTF or not. If it comes from a GLTF, then the vertex data is RH and a negative determinant world would make it a LH and _not need conversion_. Whether if is any other kind of vertex data, then it is LH, and a negative determinant would convert to RH and need conversion. I made a diagram with two nodes to help me visualize this, since the example I work on has two nodes:
image

This looks tricky... do we need to add some kind of new property to save the vertex data's handedness? If so, whenever we bake a transformation in the vertices we also need to make sure the handedness is consistent.

Comment (carolhmj) [reply src/Meshes/mesh.ts:4507]: Oh somehow Github didn't update and didn't show me @deltakosh and @Popov72 's messages O.O
We could assume that when `scene.useRightHandedSystem` is true then all of the scene's vertex data is right handed, then this could work... but I think MeshBuilder always creates vertex data in LHS, which would cause problems

Comment (deltakosh) [reply src/Meshes/mesh.ts:4507]: > MeshBuilder always creates vertex data in LHS
Then then will be displayed wrong in RH mode

Comment (sebavan) [reply src/Meshes/mesh.ts:4507]: I think it renders correctly cause the material is reversing the side orientation if no override exists.

Comment (sebavan) [reply src/Meshes/mesh.ts:4507]: Basically I wonder if the check should be a combination of side orientation and work matrix determinant sign ???

Comment (Popov72) [reply src/Meshes/mesh.ts:4507]: As @sebavan said, the lhs meshes are still rendered correctly in rhs mode because the side orientation is automatically reversed (see the constructor of `Material`).

I don't think the matrix determinant sign will help because it is not a way to know if a geometry is lhs or rhs: we can have a mesh with a lhs geometry that will either have a -1 or +1 determinant, and same thing with a rhs geometry, depending on the setup. I don't think factoring the side orientation will help. For eg, we can imagine we want to render a mesh inside-out (for whatever reason), so we would use the reverse side orientation we would have used to render the mesh normally. So, we can have any combination of matrix determinants and side orientations, even for a lhs mesh.

In my opinion, in the global case there's no way to know if a geometry is lhs or rhs, as it relies on the vertex coordinate values and the side orientation value. But the side orientation value itself is of no help because its value depends on the way you order the indices of the triangle: you can use an order and set the orientation to CCW (for eg), or order the other way around (CW) and set the orientation to CW.

We can only deal with what we know:
* all meshes created by the mesh builder are in lhs mode, so nothing to do
* all meshes loaded by glTF are rhs, and depending on `scene.useRightHandedSystem` there's a transformation that transforms them to lhs or not => `mesh.overrideMaterialSideOrientation` allows us to know when that happens

Comment (carolhmj) [reply src/Meshes/mesh.ts:4507]: So @Popov72 should we keep the check the way it is now?

File: src/Meshes/abstractMesh.ts (hunk 2 above)
Comment (carolhmj) [reply src/Meshes/abstractMesh.ts]: Fixed!

File: src/Collisions/collider.ts (hunk 1 above)
Comment (carolhmj) [reply src/Collisions/collider.ts]: Fixed!

File: src/Meshes/mesh.ts (hunk 3 above)
Comment (deltakosh) [reply src/Meshes/mesh.ts:4507]: let's keep it like this and if we find issues we will fix them

**Review by deltakosh — APPROVED** [review]
