### PR TITLE
Gizmos fixes and small improvements

### LINKED ISSUE #12718: BoundingBoxGizmo attaching to wrong child bounding box
Related forum issue: https://forum.babylonjs.com/t/boundingboxgizmo-attach-to-child-node-with-a-wrong-boundingbox/31082

### PR DESCRIPTION
**Pull request by CedricGuillemet**
fixes for :
- https://forum.babylonjs.com/t/gizmos-ondragobservable-outdated-docs/44455
- https://forum.babylonjs.com/t/boundingboxgizmo-attach-to-child-node-with-a-wrong-boundingbox/31082/19
- https://forum.babylonjs.com/t/gizmo-rotation-validation-does-not-work/44543/3
- https://forum.babylonjs.com/t/gizmo-use-tmpparent-but-do-not-preserve-scaling-sign/29270/52

fixes #12718

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14365/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14365/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14365/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14365/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14365/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14365/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14365/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14365/merge#BCU1XR#0

File: packages/dev/core/src/Gizmos/boundingBoxGizmo.ts [hunk 1]
```diff
@@ -473,13 +473,15 @@ export class BoundingBoxGizmo extends Gizmo implements IBoundingBoxGizmo {
                             this._anchorMesh.position.copyFrom(this.attachedMesh.position);
                         }
                         // Rotate around center of bounding box
-                        this._anchorMesh.addChild(this.attachedMesh, Gizmo.PreserveScaling);
```
Comment (RaananW) [inline packages/dev/core/src/Gizmos/boundingBoxGizmo.ts:476]: Is removing PreserveScaling a breaking change? Or is it the default value?

File: packages/dev/core/src/Gizmos/gizmo.ts [hunk 2]
```diff
@@ -332,6 +332,7 @@ export class Gizmo implements IGizmo {
                     effectiveNode.getClassName() === "InstancedMesh";
                 const transformNode = supportedNode ? (effectiveNode as TransformNode) : undefined;
                 effectiveNode.getWorldMatrix().decompose(undefined, this._rootMesh.rotationQuaternion!, undefined, Gizmo.PreserveScaling ? transformNode : undefined);
+                this._rootMesh.rotationQuaternion?.normalize();
```
Comment (RaananW) [inline packages/dev/core/src/Gizmos/gizmo.ts:335]: if you are sure it is defined use `!` instead of `?`, because `?` will generate unneeded code:

```suggestion
                this._rootMesh.rotationQuaternion!.normalize();
```

File: packages/dev/core/src/Gizmos/boundingBoxGizmo.ts (hunk 1 above)
Comment (CedricGuillemet) [reply packages/dev/core/src/Gizmos/boundingBoxGizmo.ts:476]: default value

**Review by Popov72 — APPROVED** [review]
