### PR TITLE
Fix VR button placement

### LINKED ISSUE #6598: Improvements to VR Button
[The move to bottom right](https://github.com/BabylonJS/Babylon.js/blob/12a5f9b7ce49c8111cd14fea6254f19dffca5bed/src/Cameras/VR/vrExperienceHelper.ts#L925-L926) code doesn't always works. Both `canvas.top` and `offsetTop` don't always return the absolute position. In our canvas they both return zero. Instead you should rely on `getBoundingClientRect()`.

Another improvement is exposing the button itself. This will allow us to hide and show the button at will.

### PR DESCRIPTION
**Pull request by haroldma**
Fixes #6598

### CODE REVIEW

File: src/Cameras/VR/vrExperienceHelper.ts [hunk 1]
```diff
@@ -616,6 +616,13 @@ export class VRExperienceHelper {
         return this._vrDeviceOrientationCamera;
     }
 
+    /**
+     * The html button that is used to trigger entering into VR.
+     */
+    public get vrButton(): HTMLButtonElement | undefined {
```
Comment (deltakosh) [inline src/Cameras/VR/vrExperienceHelper.ts]: Can you use Nullable<HTMLButtonElement > (and flat the internal button the same way?

**Comment by deltakosh** [comment]
It broke the build. I';ll take care of it
